import React, { useState } from 'react';
import type { InteractiveComponentProps } from '../../types';
import { useAuth } from '../../hooks/useAuth';
import { getAiClient } from '../../services/aiService';
import { SparklesIcon } from '../icons/SparklesIcon';
import { Modality } from '@google/genai';

const CompositorCanvasPro: React.FC<InteractiveComponentProps> = ({ interactiveId }) => {
    const { user, addPoints, updateProgress } = useAuth();
    const [source1, setSource1] = useState('A photorealistic image of a majestic lion in the savanna');
    const [source2, setSource2] = useState('A cyberpunk city street at night, neon signs reflecting in puddles');
    const [imageUrl, setImageUrl] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const hasCompleted = user?.progress.completedInteractives.includes(interactiveId);

    const handleGenerate = async () => {
        if (!source1.trim() || !source2.trim()) {
            setError('Please describe two source images.');
            return;
        }
        setLoading(true);
        setError('');
        setImageUrl('');

        const prompt = `Create a single, coherent, visually stunning image that masterfully blends the following two concepts:
    
Concept A: "${source1}"
Concept B: "${source2}"

The final image should feel unified in style, lighting, and composition.`;

        try {
            const ai = await getAiClient();
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: { parts: [{ text: prompt }] },
                config: {
                    responseModalities: [Modality.IMAGE],
                },
            });

            let foundImage = false;
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    setImageUrl(`data:image/png;base64,${part.inlineData.data}`);
                    foundImage = true;
                    if (!hasCompleted) {
                        addPoints(25);
                        updateProgress(interactiveId, 'interactive');
                    }
                    break;
                }
            }
            if (!foundImage) {
                setError('The model did not return an image. Try different descriptions.');
            }
        } catch (e) {
            console.error(e);
            setError('Failed to generate the composition.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="my-8 p-6 bg-brand-bg rounded-2xl shadow-neumorphic-out">
            <h4 className="font-bold text-lg text-brand-text mb-2 text-center">Compositor Canvas Pro</h4>
            <p className="text-center text-brand-text-light mb-4 text-sm">Describe two images, and Nano-Banana will generate a composite scene that blends them together.</p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                    <label className="font-semibold text-sm text-brand-text">Source Image A</label>
                    <textarea value={source1} onChange={e => setSource1(e.target.value)} rows={3} className="w-full mt-1 p-2 bg-brand-bg rounded-lg shadow-neumorphic-in"/>
                </div>
                 <div>
                    <label className="font-semibold text-sm text-brand-text">Source Image B</label>
                    <textarea value={source2} onChange={e => setSource2(e.target.value)} rows={3} className="w-full mt-1 p-2 bg-brand-bg rounded-lg shadow-neumorphic-in"/>
                </div>
            </div>
            
            <div className="text-center">
                 <button onClick={handleGenerate} disabled={loading} className="inline-flex items-center justify-center gap-2 bg-brand-primary text-white font-bold py-3 px-6 rounded-full shadow-neumorphic-out hover:shadow-neumorphic-in disabled:opacity-50">
                    <SparklesIcon />
                    {loading ? 'Compositing...' : 'Generate Composition'}
                </button>
            </div>
            
            {error && <p className="text-center text-red-500 mt-4">{error}</p>}
            
            {(loading || imageUrl) && (
                 <div className="mt-6 p-4 bg-brand-bg rounded-lg shadow-neumorphic-in">
                    <h5 className="font-semibold text-brand-text mb-2 text-center">Composite Scene</h5>
                    {loading && <div className="h-64 bg-brand-bg shadow-neumorphic-in rounded-lg animate-pulse flex items-center justify-center text-brand-text-light">Generating...</div>}
                    {imageUrl && <img src={imageUrl} alt="Composite scene generated by AI" className="rounded-lg shadow-md mx-auto max-h-[400px]" />}
                </div>
            )}
        </div>
    );
};

export default CompositorCanvasPro;