import type { ProgramInfo } from './types';

export const programs: ProgramInfo[] = [
    {
        id: 'vanguard',
        name: 'ZEN Vanguard',
        description: 'Professional operator track for adults, career changers, and technical builders.',
        route: '/dashboard',
        accentColor: 'purple',
        badge: 'Flagship',
        icon: 'VA',
        audience: 'Adults, workforce learners, founders, operators',
        level: 'Intermediate to advanced',
        duration: '4 modules, self-paced',
        spotlight: 'From AI user to production-minded deployer.',
        skills: ['AI foundations', 'Agents and automation', 'Deployment patterns', 'Governance'],
        outcomes: [
            'Build a durable mental model of how modern AI systems work.',
            'Design tool-using agents and simple automations with human review.',
            'Ship projects with better security, evaluation, and delivery discipline.',
        ],
        starterSteps: [
            'Read the Starter Guide to learn the shared language of AI, LLMs, and automation.',
            'Pick one module and finish it end-to-end before exploring everything else.',
            'Treat every lab like a production exercise: define the goal, build, test, document.',
        ],
    },
    {
        id: 'pioneer',
        name: 'AI Pioneer Program',
        description: 'Beginner-first AI literacy for ages 11-18 with a real build-and-publish path.',
        route: '/programs/pioneer',
        accentColor: 'blue',
        badge: 'Best place to start',
        icon: 'PI',
        audience: 'Ages 11-18, first-time builders, clubs, schools',
        level: 'Beginner',
        duration: '4 modules, project-based',
        spotlight: 'Zero-background path to AI, LLMs, automation, and a first shipped app.',
        skills: ['AI basics', 'LLM basics', 'Prompting', 'Automation concepts', 'Hugging Face deployment'],
        outcomes: [
            'Explain the difference between AI, machine learning, and LLMs in plain language.',
            'Use AI tools safely and responsibly with the right privacy habits.',
            'Build a simple app and publish it as a Hugging Face Space using an API key stored as a secret.',
        ],
        starterSteps: [
            'Start with the overview, then finish Module 1 before touching advanced tools.',
            'Use the Starter Guide section on Hugging Face Spaces when you reach deployment.',
            'Document one finished project with screenshots, prompt examples, and what you learned.',
        ],
    },
    {
        id: 'homeschool',
        name: 'AI Pioneer Homeschool Kit',
        description: 'Structured AI curriculum with routines, projects, and transcript-friendly documentation.',
        route: '/programs/homeschool',
        accentColor: 'emerald',
        badge: null,
        icon: 'HS',
        audience: 'Homeschool families and self-directed learners',
        level: 'Beginner to intermediate',
        duration: 'Semester-ready pacing',
        spotlight: 'A complete schedule, not just a collection of lessons.',
        skills: ['Planning', 'Project-based learning', 'Portfolio building', 'Transcript evidence'],
        outcomes: [
            'Run a repeatable weekly AI learning rhythm without guesswork.',
            'Build portfolio evidence that can support homeschool assessment.',
            'Translate projects into credits, reflections, and external proof of work.',
        ],
        starterSteps: [
            'Set your weekly rhythm before choosing advanced projects.',
            'Keep one running portfolio document for screenshots and reflections.',
            'Review the Starter Guide before the first deployment task.',
        ],
    },
    {
        id: 't3',
        name: 'Train-the-Trainer (T3)',
        description: 'Certification for educators and facilitators delivering ZEN programs at scale.',
        route: '/programs/t3',
        accentColor: 'amber',
        badge: null,
        icon: 'T3',
        audience: 'Educators, facilitators, administrators',
        level: 'Intermediate',
        duration: '4 modules, implementation-focused',
        spotlight: 'Turn content knowledge into safe and repeatable delivery.',
        skills: ['Facilitation', 'Assessment', 'Safety protocols', 'Program operations'],
        outcomes: [
            'Deliver ZEN curriculum with clearer pedagogy and accessibility coverage.',
            'Use repeatable lesson structures, rubrics, and safety guardrails.',
            'Scale programs without losing quality or operational visibility.',
        ],
        starterSteps: [
            'Review the safety standards before adapting any lesson.',
            'Map your delivery context: in-person, hybrid, or online.',
            'Use the rubric and documentation sections as your implementation backbone.',
        ],
    },
    {
        id: 'web3',
        name: 'Web3 & Blockchain Literacy',
        description: 'Digital identity, wallets, credentials, and trust systems without the hype.',
        route: '/programs/web3',
        accentColor: 'cyan',
        badge: null,
        icon: 'W3',
        audience: 'Beginners who need practical Web3 literacy',
        level: 'Beginner to intermediate',
        duration: '4 modules, concept-to-application',
        spotlight: 'Understand what is useful, what is risky, and what is noise.',
        skills: ['Wallet safety', 'Identity systems', 'Verifiable credentials', 'Trust models'],
        outcomes: [
            'Explain blockchains and wallets in practical terms.',
            'Protect credentials and identity using better operational hygiene.',
            'Understand how verifiable proof can support AI education and hiring.',
        ],
        starterSteps: [
            'Do not start by buying anything. Start with identity and safety.',
            'Practice with test environments before touching anything permanent.',
            'Connect the credential lessons back to your portfolio and proof of work.',
        ],
    },
    {
        id: 'arena',
        name: 'ZEN Arena',
        description: 'Model testing, prompt evaluation, and deployment patterns used by working teams.',
        route: '/programs/arena',
        accentColor: 'pink',
        badge: 'Experimentation lab',
        icon: 'AR',
        audience: 'Builders comparing models, prompts, and tools',
        level: 'Intermediate',
        duration: '4 modules, experimentation-focused',
        spotlight: 'Learn how to test instead of guessing.',
        skills: ['Model comparison', 'Prompt evaluation', 'Tool use', 'Observability'],
        outcomes: [
            'Choose models based on cost, speed, and task fit.',
            'Build a repeatable prompt evaluation workflow.',
            'Move prototypes toward production with error handling and monitoring.',
        ],
        starterSteps: [
            'Define success criteria before changing prompts or models.',
            'Run small experiments and keep notes on what changed.',
            'Use the Starter Guide deployment checklist when you publish results.',
        ],
    },
    {
        id: 'hermes',
        name: 'Hermes Agent Ops',
        description: 'Deploy and master the free, open-source Hermes AI Agent — self-evolving, multi-platform, self-hosted.',
        route: '/programs/hermes',
        accentColor: 'orange',
        badge: '🔥 Free & Open Source',
        icon: 'HA',
        audience: 'Builders, operators, and anyone who wants a personal AI agent for free',
        level: 'Beginner to advanced',
        duration: '6 modules, hands-on deployment',
        spotlight: 'Your own AI agent that learns, remembers, and works across every platform — for $0.',
        skills: ['Self-hosted AI agents', 'Multi-platform gateway', 'Persistent memory', 'Tool orchestration', 'Local LLM integration'],
        outcomes: [
            'Deploy a fully operational Hermes Agent on your own hardware or a $5 VPS.',
            'Connect your agent to Telegram, Discord, Slack, and WhatsApp with unified memory.',
            'Build custom tools, wire up MCP servers, and run autonomous scheduled workflows.',
        ],
        starterSteps: [
            'Install Hermes Agent with a single command and run your first conversation.',
            'Connect at least one messaging platform via the gateway before moving to advanced tools.',
            'Set up Ollama for free local inference before paying for any API keys.',
        ],
    },
];

export const getProgramById = (id: string): ProgramInfo | undefined => {
    return programs.find((program) => program.id === id);
};

export const getAccentClasses = (color: ProgramInfo['accentColor']) => {
    const classes = {
        purple: {
            gradient: 'from-purple-500 via-purple-600 to-violet-600',
            bg: 'bg-purple-500',
            text: 'text-purple-400',
            border: 'border-purple-500/30',
            shadow: 'shadow-glowing',
            ring: 'ring-purple-500/20',
        },
        blue: {
            gradient: 'from-blue-500 via-blue-600 to-cyan-600',
            bg: 'bg-blue-500',
            text: 'text-blue-400',
            border: 'border-blue-500/30',
            shadow: 'shadow-glowing-blue',
            ring: 'ring-blue-500/20',
        },
        emerald: {
            gradient: 'from-emerald-500 via-emerald-600 to-teal-600',
            bg: 'bg-emerald-500',
            text: 'text-emerald-400',
            border: 'border-emerald-500/30',
            shadow: 'shadow-glowing-green',
            ring: 'ring-emerald-500/20',
        },
        amber: {
            gradient: 'from-amber-500 via-amber-600 to-orange-600',
            bg: 'bg-amber-500',
            text: 'text-amber-400',
            border: 'border-amber-500/30',
            shadow: 'shadow-glowing-amber',
            ring: 'ring-amber-500/20',
        },
        cyan: {
            gradient: 'from-cyan-500 via-cyan-600 to-blue-600',
            bg: 'bg-cyan-500',
            text: 'text-cyan-400',
            border: 'border-cyan-500/30',
            shadow: 'shadow-glowing-cyan',
            ring: 'ring-cyan-500/20',
        },
        pink: {
            gradient: 'from-pink-500 via-pink-600 to-rose-600',
            bg: 'bg-pink-500',
            text: 'text-pink-400',
            border: 'border-pink-500/30',
            shadow: 'shadow-glowing',
            ring: 'ring-pink-500/20',
        },
        orange: {
            gradient: 'from-orange-500 via-orange-600 to-red-600',
            bg: 'bg-orange-500',
            text: 'text-orange-400',
            border: 'border-orange-500/30',
            shadow: 'shadow-glowing-amber',
            ring: 'ring-orange-500/20',
        },
    };

    return classes[color];
};
