import type { ProgramCurriculum } from '../../types';

export const hermesCurriculum: ProgramCurriculum = {
    title: 'Hermes Agent Ops',
    description: 'Deploy and master the free, open-source Hermes AI Agent — from first install to production-grade autonomous workflows.',
    sections: [
        {
            id: 'mod1',
            title: 'Module 1: Install & First Contact',
            icon: '🚀',
            content: [
                { type: 'heading', content: 'Why Hermes Agent' },
                { type: 'paragraph', content: 'Hermes Agent by Nous Research is the most talked-about open-source AI agent of 2026. It is MIT-licensed, runs on your own hardware, and costs nothing beyond the electricity to keep it on. Unlike closed platforms, you own every byte of data your agent produces.' },
                { type: 'paragraph', content: 'What makes Hermes different from other AI tools is its closed learning loop — every task the agent completes feeds back into a growing skill library. The agent literally gets smarter the more you use it. No other free tool does this.' },
                { type: 'heading', content: 'One-Command Install' },
                { type: 'paragraph', content: 'Hermes installs with a single command. On macOS or Linux, open a terminal and run the install script. On Windows, use WSL2 (Windows Subsystem for Linux) — Hermes runs natively in the Linux layer with zero performance penalty.' },
                { type: 'list', content: [
                    'Clone the repository or use the official install script',
                    'The installer creates a Python virtual environment automatically',
                    'All dependencies resolve in under 60 seconds on a modern machine',
                    'First run triggers the setup wizard — walk through it once and you are operational',
                ] },
                { type: 'heading', content: 'Configuration Basics' },
                { type: 'paragraph', content: 'Hermes uses two files for configuration. The first is config.yaml in ~/.hermes/ which controls behavior settings — model selection, display preferences, terminal working directory, and feature flags. The second is .env in the same directory, reserved exclusively for secrets like API keys.' },
                { type: 'quote', content: 'Rule: API keys and tokens go in .env. Everything else — timeouts, display settings, feature toggles — goes in config.yaml. Never mix them.' },
                { type: 'heading', content: 'Choose Your Model' },
                { type: 'paragraph', content: 'Hermes is model-agnostic. You can use OpenAI, Anthropic, Google, Mistral, or any OpenRouter-compatible provider. For zero-cost operation, install Ollama and run models locally — Hermes connects to your local Ollama endpoint out of the box.' },
                { type: 'list', content: [
                    'OpenAI: Set OPENAI_API_KEY in .env — supports GPT-4.1 and all latest models',
                    'Anthropic: Set ANTHROPIC_API_KEY — Claude 4 family fully supported',
                    'OpenRouter: Access 200+ models through a single API key',
                    'Ollama (free): Install Ollama, pull a model, point Hermes at localhost:11434',
                    'vLLM / local endpoints: Any OpenAI-compatible API works',
                ] },
                { type: 'heading', content: 'Your First Conversation' },
                { type: 'paragraph', content: 'Run hermes in your terminal to start the interactive CLI. Type a message and watch the agent respond. Try asking it to search the web, write a file, or explain a concept. Notice the kawaii spinner faces while it thinks — that is the signature Hermes experience.' },
            ],
        },
        {
            id: 'mod2',
            title: 'Module 2: The Closed Learning Loop',
            icon: '🧠',
            content: [
                { type: 'heading', content: 'The Feature Everyone Is Talking About' },
                { type: 'paragraph', content: 'The closed learning loop is what separates Hermes from every other AI assistant. After completing a task, the agent evaluates the process, extracts reusable patterns, and saves them as skills. The next time it encounters a similar task, it pulls those refined skills automatically — making it faster, more accurate, and more personalized with every interaction.' },
                { type: 'paragraph', content: 'This is not prompt caching or simple memory. The agent genuinely evolves its behavior over time. A Hermes instance that has been running for a month is measurably better than a fresh install for the tasks its operator cares about.' },
                { type: 'heading', content: 'How Skills Work' },
                { type: 'list', content: [
                    'Skills are stored in ~/.hermes/skills/ as structured files',
                    'The agent extracts skills automatically after successful task completion',
                    'Skills are injected as user messages (not system prompt) to preserve prompt caching',
                    'You can browse, edit, and manage skills using slash commands',
                    'Optional skills in optional-skills/ can be installed on demand for specialized capabilities',
                ] },
                { type: 'heading', content: 'Persistent Memory & User Modeling' },
                { type: 'paragraph', content: 'Hermes maintains long-term memory across sessions using pluggable memory providers. It builds a model of you — your preferences, decision history, communication style, common tasks — and injects this context into every conversation. The agent remembers what you told it last week and adapts accordingly.' },
                { type: 'list', content: [
                    'Multiple memory backends: honcho, mem0, supermemory, holographic, and more',
                    'Configure your provider in config.yaml under memory.provider',
                    'Memory syncs after each conversation turn via sync_turn()',
                    'Prefetch queries pull relevant memories before the agent responds',
                    'Each memory provider has its own CLI commands for inspection and management',
                ] },
                { type: 'heading', content: 'Session Continuity' },
                { type: 'paragraph', content: 'Sessions are persisted in a SQLite database with FTS5 full-text search. You can resume any previous conversation, search across all sessions, and maintain context across restarts. The /resume command picks up exactly where you left off.' },
                { type: 'quote', content: 'The combination of skills + memory + sessions means your Hermes agent is a persistent digital entity, not a stateless chatbot. It accumulates institutional knowledge about your work.' },
            ],
        },
        {
            id: 'mod3',
            title: 'Module 3: Multi-Platform Gateway',
            icon: '📡',
            content: [
                { type: 'heading', content: 'One Agent, Every Platform' },
                { type: 'paragraph', content: 'The Hermes gateway is a single process that connects your agent to 15+ messaging platforms simultaneously. You interact with the same agent — same memory, same skills, same context — whether you message it on Telegram from your phone, Discord from your desktop, or the terminal CLI from your laptop.' },
                { type: 'heading', content: 'Supported Platforms' },
                { type: 'list', content: [
                    'Telegram — the most popular choice; supports bot commands, inline responses, and media',
                    'Discord — full server integration with slash commands and thread support',
                    'Slack — workspace integration via the Hermes bot app',
                    'WhatsApp — personal and business messaging through supported bridges',
                    'Signal — privacy-focused secure messaging',
                    'Matrix — federated, self-hosted chat protocol',
                    'Mattermost — open-source Slack alternative for teams',
                    'Email — your agent reads and responds to emails',
                    'SMS — text message interface for mobile-first workflows',
                    'Home Assistant — voice and automation integration for smart homes',
                    'DingTalk, WeCom, Weixin, Feishu, QQBot — full CJK platform coverage',
                    'Webhook / API Server — build custom integrations with any service',
                ] },
                { type: 'heading', content: 'Setting Up Telegram (Quickstart)' },
                { type: 'paragraph', content: 'Telegram is the fastest gateway to set up. Create a bot via @BotFather, copy the token into your .env file as TELEGRAM_BOT_TOKEN, enable the telegram platform in config.yaml, and run hermes gateway. Your agent is now live on Telegram within 60 seconds.' },
                { type: 'heading', content: 'Unified Context' },
                { type: 'paragraph', content: 'The killer feature of the gateway is unified context. A conversation you started on Telegram continues seamlessly on Discord. Files you shared in Slack are remembered when you ask about them via the CLI. This is possible because every platform adapter routes through the same AIAgent core and the same session database.' },
                { type: 'heading', content: 'Cron Scheduling' },
                { type: 'paragraph', content: 'Hermes includes a built-in cron scheduler. Define recurring jobs — daily news summaries, weekly report generation, automated monitoring checks — and the agent executes them autonomously on schedule. Results are delivered to whichever platform you configure.' },
                { type: 'list', content: [
                    'Jobs defined in the cron/ module with scheduler.py orchestration',
                    'Supports standard cron expressions for flexible timing',
                    'Output can route to any connected gateway platform',
                    'Human-in-the-loop approval gates for high-risk scheduled actions',
                ] },
            ],
        },
        {
            id: 'mod4',
            title: 'Module 4: Tool Ecosystem & MCP',
            icon: '🔧',
            content: [
                { type: 'heading', content: '40+ Built-In Tools' },
                { type: 'paragraph', content: 'Hermes ships with over 40 tools out of the box, organized into toolsets. Each tool auto-registers via the tools/registry.py discovery system — drop a Python file in the tools/ directory with a registry.register() call and it is immediately available to the agent.' },
                { type: 'list', content: [
                    'Web search — real-time internet queries with source citations',
                    'Browser automation — navigate pages, click elements, fill forms, take screenshots',
                    'Vision — analyze images, screenshots, diagrams with multimodal models',
                    'File operations — read, write, edit, search across your filesystem',
                    'Code execution — run Python, shell commands, and scripts safely',
                    'Todo management — persistent task lists tracked across sessions',
                    'Terminal environments — local, Docker, SSH, Modal, Daytona, Singularity',
                ] },
                { type: 'heading', content: 'Building Custom Tools' },
                { type: 'paragraph', content: 'Adding a new tool requires changes in exactly 2 files. First, create tools/your_tool.py with a handler function and a registry.register() call. Second, add your tool to a toolset in toolsets.py. That is it — the auto-discovery system handles everything else.' },
                { type: 'quote', content: 'All tool handlers MUST return a JSON string. The registry handles schema collection, dispatch, availability checking, and error wrapping automatically.' },
                { type: 'heading', content: 'Model Context Protocol (MCP)' },
                { type: 'paragraph', content: 'MCP is the open standard for connecting AI agents to external data sources and tools. Hermes supports MCP natively, meaning you can wire up any MCP-compatible server — databases, APIs, knowledge bases, code repositories — and the agent can use them as if they were built-in tools.' },
                { type: 'paragraph', content: 'This is how you give your Hermes agent access to virtually unlimited capabilities without writing custom tool code. The MCP ecosystem is growing rapidly and Hermes can tap into all of it.' },
                { type: 'heading', content: 'Toolsets & Availability' },
                { type: 'list', content: [
                    'Tools are grouped into toolsets defined in toolsets.py',
                    '_HERMES_CORE_TOOLS are available on all platforms by default',
                    'Enable or disable toolsets per-session with enabled_toolsets / disabled_toolsets',
                    'Tools can declare environment variable requirements via requires_env',
                    'check_fn functions gate tool availability on runtime conditions',
                ] },
            ],
        },
        {
            id: 'mod5',
            title: 'Module 5: Self-Hosted Production Ops',
            icon: '🏠',
            content: [
                { type: 'heading', content: 'Run It on Your Own Hardware' },
                { type: 'paragraph', content: 'One of the most exciting things about Hermes is that you do not need to pay anyone a subscription fee. The agent itself is free. You only pay for LLM API calls when the agent is actively thinking — and even that cost disappears if you run local models with Ollama.' },
                { type: 'heading', content: 'WSL2 Local Setup (Windows)' },
                { type: 'list', content: [
                    'Enable WSL2 from Windows Features or via wsl --install',
                    'Install Ubuntu 22.04+ from the Microsoft Store',
                    'Install Python 3.11+, pip, and git inside WSL',
                    'Clone hermes-agent and run the setup wizard',
                    'Install Ollama inside WSL for local model inference',
                    'Models like Llama 3.3, Mistral, and Qwen run well on 16GB+ RAM laptops',
                ] },
                { type: 'heading', content: '$5 VPS Deployment' },
                { type: 'paragraph', content: 'For always-on operation, deploy Hermes to a cheap VPS. A $5/month server from DigitalOcean, Hetzner, or Vultr is more than enough. Use systemd to keep the gateway running 24/7, configure your messaging platform tokens, and you have a persistent AI agent accessible from anywhere.' },
                { type: 'list', content: [
                    'Provision a 1-2 vCPU, 2GB RAM VPS with Ubuntu',
                    'Clone the repo, run the install, configure .env with your API keys',
                    'Create a systemd service for hermes gateway',
                    'Set up log rotation for ~/.hermes/logs/',
                    'Optional: use a reverse proxy for the API server endpoint',
                ] },
                { type: 'heading', content: 'Ollama for Free Local Inference' },
                { type: 'paragraph', content: 'Ollama lets you run LLMs locally with zero API costs. Install it alongside Hermes, pull a model (ollama pull llama3.3), and point Hermes at localhost:11434. For coding tasks, use Qwen 2.5 Coder. For general conversation, Llama 3.3 or Mistral deliver excellent results.' },
                { type: 'heading', content: 'Open WebUI Integration' },
                { type: 'paragraph', content: 'Open WebUI gives you a browser-based ChatGPT-like interface for your local Hermes setup. Install it alongside Ollama for a polished web interface that your family or team can use without touching a terminal.' },
                { type: 'heading', content: 'Security Hardening' },
                { type: 'list', content: [
                    'API keys and tokens live in .env only — never in config.yaml or code',
                    'Use credential pools for rotating keys across multiple providers',
                    'Gate high-risk tool actions through human approval checkpoints',
                    'The gateway supports session tokens for API authentication',
                    'Review ~/.hermes/logs/errors.log regularly for anomalies',
                ] },
            ],
        },
        {
            id: 'mod6',
            title: 'Module 6: Advanced Agent Patterns',
            icon: '⚡',
            content: [
                { type: 'heading', content: 'Subagents & Parallel Execution' },
                { type: 'paragraph', content: 'Hermes can spawn subagents — child agent instances that handle subtasks in parallel while the main agent continues orchestrating. This is how complex multi-step workflows get executed efficiently. The main agent delegates research, code generation, and analysis to subagents and synthesizes the results.' },
                { type: 'heading', content: 'Batch Processing' },
                { type: 'paragraph', content: 'The batch_runner.py module enables parallel processing of multiple tasks. Feed Hermes a list of inputs and it processes them concurrently, respecting rate limits and budget constraints. Perfect for bulk content generation, data analysis, or automated testing workflows.' },
                { type: 'heading', content: 'Plugin System' },
                { type: 'paragraph', content: 'Hermes has a full plugin architecture. Plugins can register lifecycle hooks (pre_tool_call, post_tool_call, pre_llm_call, post_llm_call, on_session_start, on_session_end), register new tools, and add CLI subcommands. Drop a plugin in ~/.hermes/plugins/ or install via pip entry points.' },
                { type: 'list', content: [
                    'Memory plugins: honcho, mem0, supermemory, holographic, and more',
                    'Context engine plugins for custom retrieval strategies',
                    'Image generation plugins for creative workflows',
                    'Dashboard plugin for web-based monitoring',
                    'Plugins must NOT modify core files — extend via hooks and the ctx API',
                ] },
                { type: 'heading', content: 'TUI & Dashboard' },
                { type: 'paragraph', content: 'The hermes --tui flag launches a full terminal UI built with Ink (React for the terminal). It provides a rich interactive experience with streaming responses, tool activity visualization, approval prompts, session management, and theming. The dashboard (hermes dashboard) embeds this TUI in a web browser alongside monitoring widgets.' },
                { type: 'heading', content: 'Skin & Theme Engine' },
                { type: 'paragraph', content: 'Hermes includes a data-driven skin engine for visual customization. Switch between built-in skins (default gold/kawaii, ares crimson, mono grayscale, slate blue) or create your own YAML skin file. Customize banner colors, spinner animations, tool emojis, branding text, and more — all without touching code.' },
                { type: 'quote', content: 'The combination of subagents, plugins, gateway, memory, and the learning loop makes Hermes one of the most capable personal AI systems available — and it is completely free.' },
            ],
        },
    ],
};
