create table if not exists public.user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null unique,
    name text not null,
    picture text,
    total_points integer not null default 0,
    final_certification_id text,
    final_certification_hash text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.module_progress (
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    module_id smallint not null check (module_id between 1 and 4),
    completed_sections text[] not null default '{}',
    completed_interactives text[] not null default '{}',
    points integer not null default 0,
    started_at timestamptz,
    completed_at timestamptz,
    last_viewed_section text not null default 'overview',
    certificate_id text,
    certificate_hash text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, module_id)
);

create table if not exists public.user_badges (
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    badge_id text not null,
    title text not null,
    description text not null,
    kind text not null check (kind in ('section', 'module', 'credential', 'streak', 'deployment')),
    module_id smallint check (module_id between 1 and 4),
    earned_at timestamptz not null default now(),
    primary key (user_id, badge_id)
);

create table if not exists public.session_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    module_id smallint not null check (module_id between 1 and 4),
    started_at timestamptz not null,
    ended_at timestamptz not null,
    sections_viewed text[] not null default '{}',
    created_at timestamptz not null default now()
);

create table if not exists public.user_activity_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.user_profiles(id) on delete cascade,
    type text not null,
    description text not null,
    module_id smallint check (module_id between 1 and 4),
    points integer,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.certificates (
    id text primary key,
    type text not null check (type in ('module', 'final')),
    module_number smallint check (module_number between 1 and 4),
    user_name text not null,
    user_email text not null,
    issued_at timestamptz not null,
    performance jsonb not null,
    sha256_hash text not null,
    block_number integer not null,
    previous_hash text not null,
    artifact_url text,
    badge_id text,
    created_at timestamptz not null default now()
);

create index if not exists module_progress_user_idx on public.module_progress (user_id);
create index if not exists session_history_user_created_idx on public.session_history (user_id, created_at desc);
create index if not exists user_activity_events_user_created_idx on public.user_activity_events (user_id, created_at desc);
create index if not exists certificates_user_email_idx on public.certificates (user_email, issued_at desc);

alter table public.user_profiles enable row level security;
alter table public.module_progress enable row level security;
alter table public.user_badges enable row level security;
alter table public.session_history enable row level security;
alter table public.user_activity_events enable row level security;
alter table public.certificates enable row level security;

create or replace function public.is_zen_vanguard_admin()
returns boolean
language sql
stable
set search_path = public
as $$
    select
        coalesce(((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin', false)
        or lower(coalesce((select auth.jwt()) ->> 'email', '')) in (
            'royaltokens@gmail.com',
            'huxley@zenai.biz'
        );
$$;

create policy "users read own profile" on public.user_profiles for select to authenticated using ((select auth.uid()) = id);
create policy "users create own profile" on public.user_profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "users update own profile" on public.user_profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "admins read profiles" on public.user_profiles for select to authenticated using (public.is_zen_vanguard_admin());

create policy "users read own module progress" on public.module_progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "users write own module progress" on public.module_progress for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "users update own module progress" on public.module_progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "admins read module progress" on public.module_progress for select to authenticated using (public.is_zen_vanguard_admin());

create policy "users read own badges" on public.user_badges for select to authenticated using ((select auth.uid()) = user_id);
create policy "users write own badges" on public.user_badges for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "users update own badges" on public.user_badges for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "admins read badges" on public.user_badges for select to authenticated using (public.is_zen_vanguard_admin());

create policy "users read own sessions" on public.session_history for select to authenticated using ((select auth.uid()) = user_id);
create policy "users insert own sessions" on public.session_history for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "admins read sessions" on public.session_history for select to authenticated using (public.is_zen_vanguard_admin());

create policy "users read own activity" on public.user_activity_events for select to authenticated using ((select auth.uid()) = user_id);
create policy "users insert own activity" on public.user_activity_events for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "admins read activity" on public.user_activity_events for select to authenticated using (public.is_zen_vanguard_admin());

create policy "authenticated users read own certificates" on public.certificates
    for select to authenticated using (lower((select auth.jwt()) ->> 'email') = lower(user_email) or public.is_zen_vanguard_admin());
create policy "authenticated users insert own certificates" on public.certificates
    for insert to authenticated with check (lower((select auth.jwt()) ->> 'email') = lower(user_email));
create policy "authenticated users update own certificates" on public.certificates
    for update to authenticated using (lower((select auth.jwt()) ->> 'email') = lower(user_email)) with check (lower((select auth.jwt()) ->> 'email') = lower(user_email));
